package it.polimi.ProgettoIngSW2019.common.enums;

public enum EventType {
    REQUEST_USE_POWERUP,
    REQUEST_POWERUP_AMMO,
    REQUEST_SPAWN,
    REQUEST_WEAPONS_UNLOADED,
    REQUEST_RELOAD,

    RESPONSE_REQUEST_USE_POWERUP,
    RESPONSE_REQUEST_POWERUP_AMMO,
    RESPONSE_REQUEST_SPAWN,
    RESPONSE_REQUEST_WEAPONS_UNLOADED,
    RESPONSE_REQUEST_RELOAD,
}
