package it.polimi.ProgettoIngSW2019.common.enums;

public enum EventType {
    REQUEST_USE_POWERUP,
    REQUEST_POWERUP_AMMO,
    REQUEST_SPAWN_INFO,
    REQUEST_SPAWN,
    REQUEST_INITIAL_SPAWN_INFO,
    REQUEST_RELOAD_INFO,
    REQUEST_RELOAD,
    REQUEST_ENDTURN_INFO,

    RESPONSE_REQUEST_USE_POWERUP,
    RESPONSE_REQUEST_POWERUP_AMMO,
    RESPONSE_REQUEST_SPAWN_INFO,
    RESPONSE_REQUEST_SPAWN,
    RESPONSE_REQUEST_INITIAL_SPAWN_INFO,
    RESPONSE_REQUEST_RELOAD_INFO,
    RESPONSE_REQUEST_RELOAD,
    RESPONSE_REQUEST_ENDTURN_INFO,

    SCORE_DEAD_PLAYERS,
    DOUBLE_KILL,
    LOGIN,
    CHECK_USERNAME_AVIABILITY,
    UPDATE_MY_POWERUPS,
    UPDATE_POWERUPS,
    UPDATE_MY_WEAPONS,
    UPDATE_PLAYER_INFO,
}
