package it.polimi.ProgettoIngSW2019.controller;

import com.google.gson.Gson;
import it.polimi.ProgettoIngSW2019.common.Event;
import it.polimi.ProgettoIngSW2019.common.LightModel.WeaponLM;
import it.polimi.ProgettoIngSW2019.common.Message.toController.InfoRequest;
import it.polimi.ProgettoIngSW2019.common.Message.toController.ReloadChoiceRequest;
import it.polimi.ProgettoIngSW2019.common.Message.toView.ReloadInfoResponse;
import it.polimi.ProgettoIngSW2019.common.enums.EventType;
import it.polimi.ProgettoIngSW2019.common.utilities.Observer;
import it.polimi.ProgettoIngSW2019.custom_exception.IllegalAttributeException;
import it.polimi.ProgettoIngSW2019.model.*;
import it.polimi.ProgettoIngSW2019.common.enums.AmmoType;
import it.polimi.ProgettoIngSW2019.virtual_view.VirtualView;


import java.util.ArrayList;
import java.util.List;


/**
 * Class ReloadController
 * check reload
 * reload method
 * @author Priscilla Lo Bue
 */
public class ReloadController extends Controller implements Observer<Event> {
    private WeaponCard weaponToReload;
    private Player ownerPlayer;
    private List<WeaponCard> weaponsCanReload = new ArrayList<>();
    private List<AmmoType> reloadCost = new ArrayList<>();



    /**
     * constructor
     * @param turnManager   turnManager
     * @param idConverter   idConverter
     * @param virtualView   virtualView
     */
    public ReloadController(TurnManager turnManager, IdConverter idConverter, VirtualView virtualView, CreateJson createJson, IdPlayersCreateList idPlayersCreateList) {
        super(turnManager, idConverter, virtualView, createJson, idPlayersCreateList);
    }



    /**
     * receive the message from the view
     * check type event
     * do actions based by type event
     * @param event     event sent
     */
    public void update(Event event) {
        if(event.getCommand().equals(EventType.REQUEST_WEAPONS_CAN_RELOAD)) {
            reloadInfo(event.getMessageInJsonFormat());
        }

        if(event.getCommand().equals(EventType.REQUEST_RELOAD)) {
            reloadWeapon(event.getMessageInJsonFormat());
        }
    }



    /**
     * check the info to send to reload to the view
     * @param messageJson   message json from view
     */
    public void reloadInfo(String messageJson) {
        //extract the json message in class with his data
        InfoRequest infoRequest = new Gson().fromJson(messageJson, InfoRequest.class);

        //is the turn of the player who wants to reload?
        if(infoRequest.getIdPlayer() != getTurnManager().getCurrentPlayer().getIdPlayer())
            throw new  IllegalAttributeException("It is not Player: " + infoRequest.getIdPlayer() + " turn");

        //extract player from the model with the idPlayer sent from the view
        ownerPlayer = getIdConverter().getPlayerById(infoRequest.getIdPlayer());

        //set weapons list can be reloaded based by the number of the ammo of the player
        setListWeaponsCanReload();

        if(weaponsCanReload != null) {
            List<WeaponLM> weaponsCanReloadLM = getCreateJson().createWeaponsListLM(weaponsCanReload);
            String reloadInfoString = new Gson().toJson(new ReloadInfoResponse(ownerPlayer.getIdPlayer(), weaponsCanReloadLM));
            sendInfo(EventType.RESPONSE_REQUEST_WEAPONS_CAN_RELOAD, reloadInfoString, getIdPlayersCreateList().addOneIdPlayers(ownerPlayer));
        }
        else {
            String reloadInfoString = new Gson().toJson(new ReloadInfoResponse(ownerPlayer.getIdPlayer(), null));
            sendInfo(EventType.RESPONSE_REQUEST_WEAPONS_CAN_RELOAD, reloadInfoString, getIdPlayersCreateList().addOneIdPlayers(ownerPlayer));
        }
    }



    /**
     * creates the list with the weapons can be reloaded
     */
    public void setListWeaponsCanReload() {

       for(WeaponCard weaponCard:ownerPlayer.getUnloadedWeapons()) {
           reloadCost = weaponCard.getreloadCost();

           if(ownerPlayer.hasEnoughAmmo(reloadCost))
               weaponsCanReload.add(weaponCard);
       }
    }



    /**
     * open the message and reload the weapon received
     * send the new player with the attributes modified to the view
     * @param messageJson   message json from the event generated by view
     */
    public void reloadWeapon(String messageJson) {
        ReloadChoiceRequest reloadChoice = new Gson().fromJson(messageJson, ReloadChoiceRequest.class);

        if(reloadChoice.getIdPlayer() != getTurnManager().getCurrentPlayer().getIdPlayer())
            throw new  IllegalAttributeException("It is not Player: " + reloadChoice.getIdPlayer() + " turn");

        ownerPlayer = getIdConverter().getPlayerById(reloadChoice.getIdPlayer());
        weaponToReload = getIdConverter().getUnloadedWeaponById(ownerPlayer.getIdPlayer(), reloadChoice.getIdWeaponToReload());

        if(weaponToReload == null)
            throw new IllegalAttributeException("WeaponToReload cannot be null");

        reloadCost = weaponToReload.getreloadCost();

        if(ownerPlayer.hasEnoughAmmo(reloadCost))
            ownerPlayer.reload(weaponToReload);
        else
            throw new IllegalAttributeException("The player: " + ownerPlayer.getCharaName() + "with id: " + ownerPlayer.getIdPlayer() + "cannot pay the reload cost");

        //mando al player le nuove weapons cariche
        String loadedWeaponsLMJson = getCreateJson().createMyLoadedWeaponsListLMJson(ownerPlayer);
        sendInfo(EventType.RESPONSE_REQUEST_RELOAD, loadedWeaponsLMJson, getIdPlayersCreateList().addOneIdPlayers(ownerPlayer));


        String playerLMJson = getCreateJson().createPlayerLMJson(ownerPlayer);
        sendInfo(EventType.UPDATE_PLAYER_INFO, playerLMJson, getIdPlayersCreateList().addAllIdPlayers());
    }
}